version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.2-jdk-8-alpine
    steps:
      - checkout
      - run:
          name: Runs unit tests and packages application
          command: mvn package
      - run:
          name: Build and push Docker image
          command: |
            docker build -t zuvsapp/shop-api:0.1.${CIRCLE_BUILD_NUM} .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push zuvsapp/shop-api:0.1.${CIRCLE_BUILD_NUM}