version: 2
jobs:
  build:
    docker:
      - image: maven:3.5.2-jdk-8-alpine
    steps:
      - checkout
      - run:
          name: Runs unit tests and packages application
          command: mvn package