version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Runs unit tests and packages application
          command: mvn package
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            mvn dockerfile:push